const state={projects:[],selectedId:null,sourceSha:null,pendingFile:null,imageMode:'url'};
const $=(id)=>document.getElementById(id);
const fields=['id','name','category','status','description','siteUrl','repoUrl','imageAlt'];
const els={repository:$('repository'),branch:$('branch'),token:$('token'),status:$('connectionStatus'),list:$('projectList'),form:$('projectForm'),title:$('editorTitle'),imageUrl:$('imageUrl'),imageFile:$('imageFile'),fileName:$('fileName'),technologies:$('technologies'),highlights:$('highlights'),featured:$('featured'),published:$('published'),toast:$('toast')};

function slugify(value=''){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}
function encodeBase64(text){return btoa(unescape(encodeURIComponent(text)))}
function decodeBase64(text){return decodeURIComponent(escape(atob(text.replace(/\n/g,''))))}
function splitCsv(value){return value.split(',').map(v=>v.trim()).filter(Boolean)}
function splitLines(value){return value.split('\n').map(v=>v.trim()).filter(Boolean)}
function showToast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>els.toast.classList.remove('show'),2800)}
function setStatus(message,type=''){els.status.textContent=message;els.status.className=`status ${type}`.trim()}
function repoParts(){const [owner,repo]=els.repository.value.trim().split('/');if(!owner||!repo)throw new Error('Usa el formato propietario/repositorio.');return{owner,repo}}
function headers(){const token=els.token.value.trim();return{'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(token?{'Authorization':`Bearer ${token}`}:{})}}
function selected(){return state.projects.find(p=>p.id===state.selectedId)||null}

async function githubRequest(path,options={}){const response=await fetch(`https://api.github.com${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`GitHub respondió ${response.status}`);return data}

async function loadFromGitHub(){try{setStatus('Conectando con GitHub…');const {owner,repo}=repoParts();const branch=encodeURIComponent(els.branch.value.trim()||'main');const data=await githubRequest(`/repos/${owner}/${repo}/contents/projects.json?ref=${branch}`);const parsed=JSON.parse(decodeBase64(data.content));state.projects=Array.isArray(parsed.projects)?parsed.projects:[];state.sourceSha=data.sha;sessionStorage.setItem('portfolio_admin_repo',els.repository.value.trim());sessionStorage.setItem('portfolio_admin_branch',els.branch.value.trim());if(els.token.value)sessionStorage.setItem('portfolio_admin_token',els.token.value);renderList();selectProject(state.projects[0]?.id||null);setStatus(`Conectado. ${state.projects.length} proyectos cargados.`,'success');showToast('Contenido cargado desde GitHub');}catch(error){setStatus(error.message,'error');showToast(`No se pudo conectar: ${error.message}`)}}

async function loadFallback(){try{const response=await fetch('projects.json',{cache:'no-store'});const data=await response.json();state.projects=data.projects||[];renderList();selectProject(state.projects[0]?.id||null);setStatus('Archivo projects.json cargado. Conecta GitHub para publicar.','success')}catch{state.projects=[];newProject();setStatus('Comienza creando tu primer proyecto.')}}

function blankProject(){return{id:`proyecto-${Date.now()}`,name:'Nuevo proyecto',category:'Producto digital',status:'En desarrollo',description:'',image:'',imageAlt:'',previewClass:'',siteUrl:'',repoUrl:'',technologies:[],highlights:[],featured:false,published:true}}
function newProject(){const project=blankProject();state.projects.unshift(project);renderList();selectProject(project.id);showToast('Nuevo proyecto creado')}
function duplicateProject(){const original=selected();if(!original)return;const copy={...structuredClone(original),id:`${original.id}-copia-${Date.now()}`,name:`${original.name} — copia`,featured:false};state.projects.unshift(copy);renderList();selectProject(copy.id);showToast('Proyecto duplicado')}
function deleteProject(){const project=selected();if(!project)return;if(!confirm(`¿Eliminar “${project.name}”? El cambio se aplicará al publicar.`))return;state.projects=state.projects.filter(p=>p.id!==project.id);renderList();selectProject(state.projects[0]?.id||null);showToast('Proyecto eliminado del borrador')}

function renderList(){els.list.innerHTML='';state.projects.forEach(project=>{const button=document.createElement('button');button.type='button';button.className=project.id===state.selectedId?'active':'';button.innerHTML=`<span class="list-thumb"></span><span class="list-copy"><strong></strong><span></span></span><i class="list-state ${project.published?'published':''}"></i>`;button.querySelector('strong').textContent=project.name||'Sin nombre';button.querySelector('.list-copy span').textContent=project.category||'Sin categoría';const thumb=button.querySelector('.list-thumb');if(project.image)thumb.style.backgroundImage=`url("${project.image.replace(/"/g,'%22')}")`;button.addEventListener('click',()=>selectProject(project.id));els.list.appendChild(button)})}

function selectProject(id){state.selectedId=id;state.pendingFile=null;els.imageFile.value='';els.fileName.textContent='';const project=selected();if(!project){newProject();return}fields.forEach(key=>$(key).value=project[key]||'');els.imageUrl.value=project.image||'';els.technologies.value=(project.technologies||[]).join(', ');els.highlights.value=(project.highlights||[]).join('\n');els.featured.checked=Boolean(project.featured);els.published.checked=project.published!==false;els.title.textContent=project.name||'Editar proyecto';renderList();updatePreview()}

function readForm(){const project=selected()||blankProject();fields.forEach(key=>project[key]=$(key).value.trim());project.id=slugify(project.id||project.name)||`proyecto-${Date.now()}`;project.image=els.imageUrl.value.trim();project.technologies=splitCsv(els.technologies.value);project.highlights=splitLines(els.highlights.value);project.featured=els.featured.checked;project.published=els.published.checked;return project}
function syncFormToState(){const project=readForm();const index=state.projects.findIndex(p=>p.id===state.selectedId);const previousId=state.selectedId;if(index>=0)state.projects[index]=project;else state.projects.unshift(project);state.selectedId=project.id;if(previousId!==project.id)renderList();els.title.textContent=project.name||'Editar proyecto';updatePreview()}

function updatePreview(){const project=readForm();$('previewName').textContent=project.name||'Nombre del proyecto';$('previewCategory').textContent=project.category||'Categoría';$('previewStatus').textContent=project.status||'Estado';$('previewDescription').textContent=project.description||'La descripción aparecerá aquí.';const chips=$('previewTechnologies');chips.innerHTML='';project.technologies.forEach(item=>{const span=document.createElement('span');span.textContent=item;chips.appendChild(span)});const preview=$('previewImage');preview.style.backgroundImage=project.image?`linear-gradient(rgba(15,23,42,.08),rgba(15,23,42,.08)),url("${project.image.replace(/"/g,'%22')}")`:'';preview.querySelector('span').style.display=project.image?'none':'inline-flex'}

async function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
async function uploadImage(project){if(!state.pendingFile)return project.image;const {owner,repo}=repoParts();const branch=els.branch.value.trim()||'main';const extension=(state.pendingFile.name.split('.').pop()||'webp').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`assets/projects/${slugify(project.id||project.name)}-${Date.now()}.${extension}`;const content=await fileToBase64(state.pendingFile);await githubRequest(`/repos/${owner}/${repo}/contents/${path}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Add image for ${project.name}`,content,branch})});return `/${path}`}

async function publish(){try{syncFormToState();const project=selected();if(state.pendingFile){setStatus('Subiendo imagen a GitHub…');project.image=await uploadImage(project);els.imageUrl.value=project.image;state.pendingFile=null}setStatus('Publicando projects.json…');const {owner,repo}=repoParts();const branch=els.branch.value.trim()||'main';const payload={message:'Update portfolio projects from admin panel',content:encodeBase64(JSON.stringify({projects:state.projects},null,2)),branch,...(state.sourceSha?{sha:state.sourceSha}:{})};const data=await githubRequest(`/repos/${owner}/${repo}/contents/projects.json`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.sourceSha=data.content?.sha||state.sourceSha;renderList();updatePreview();setStatus('Cambios publicados correctamente en GitHub.','success');showToast('Proyecto publicado en GitHub')}catch(error){setStatus(error.message,'error');showToast(`No se pudo publicar: ${error.message}`)}}

function saveDraft(){syncFormToState();localStorage.setItem('portfolio_projects_draft',JSON.stringify({projects:state.projects}));renderList();showToast('Borrador guardado en este navegador')}
function loadLocalFile(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));state.projects=data.projects||[];renderList();selectProject(state.projects[0]?.id||null);showToast('Archivo local cargado')}catch{showToast('El archivo JSON no es válido')}};reader.readAsText(file)}

els.form.addEventListener('input',()=>{syncFormToState();renderList()});els.form.addEventListener('submit',event=>{event.preventDefault();publish()});$('connectButton').addEventListener('click',loadFromGitHub);$('newProjectButton').addEventListener('click',newProject);$('duplicateButton').addEventListener('click',duplicateProject);$('deleteButton').addEventListener('click',deleteProject);$('saveDraftButton').addEventListener('click',saveDraft);$('loadLocalButton').addEventListener('click',()=>$('localJsonInput').click());$('localJsonInput').addEventListener('change',event=>event.target.files[0]&&loadLocalFile(event.target.files[0]));
els.imageFile.addEventListener('change',event=>{state.pendingFile=event.target.files[0]||null;els.fileName.textContent=state.pendingFile?`${state.pendingFile.name} · ${(state.pendingFile.size/1024/1024).toFixed(2)} MB`:'';if(state.pendingFile){const url=URL.createObjectURL(state.pendingFile);els.imageUrl.value=url;updatePreview()}});
document.querySelectorAll('.mode-tab').forEach(tab=>tab.addEventListener('click',()=>{state.imageMode=tab.dataset.mode;document.querySelectorAll('.mode-tab').forEach(item=>item.classList.toggle('active',item===tab));$('urlMode').classList.toggle('active',state.imageMode==='url');$('uploadMode').classList.toggle('active',state.imageMode==='upload')}));
$('name').addEventListener('blur',()=>{if(!$('id').value||$('id').value.startsWith('proyecto-'))$('id').value=slugify($('name').value);syncFormToState()});

els.repository.value=sessionStorage.getItem('portfolio_admin_repo')||els.repository.value;els.branch.value=sessionStorage.getItem('portfolio_admin_branch')||els.branch.value;els.token.value=sessionStorage.getItem('portfolio_admin_token')||'';
const localDraft=localStorage.getItem('portfolio_projects_draft');if(localDraft){try{state.projects=JSON.parse(localDraft).projects||[];renderList();selectProject(state.projects[0]?.id||null);setStatus('Borrador local recuperado. Conecta GitHub para publicar.','success')}catch{loadFallback()}}else loadFallback();
